version: "3.8"
services:
  db-stori:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_DATABASE=stori
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: