service: stori-lambda

frameworkVersion: "3"
configValidationMode: error

provider:
  name: aws
  runtime: provided.al2 # <- change from go1.x to provided.al2
  architecture: arm64   # <- change from x86_64 to arm64
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-central-1'}
  httpApi:
    cors: true
    name: ${self:service}-${self:provider.stage}

package:
  individually: true # <- package each function individually, to prevent file name conflicts

functions:
  hello:
    name: lambda-arm64
    handler: bootstrap
    package:
      artifact: build/lambda.zip
    events:
      - httpApi:
          path: /arm64/lambda
          method: post