service: golang-provided-al2-arm64

frameworkVersion: "3"
configValidationMode: error

provider:
  name: aws
  runtime: provided.al2 # <- change from go1.x to provided.al2
  architecture: arm64   # <- change from x86_64 to arm64
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-central-1'}
  httpApi:
    cors: true
    name: ${self:service}-${self:provider.stage}

functions:
  hello:
    name: hello
    handler: build/lambda/hello
    events:
      - httpApi:
          path: /arm64/hello
          method: get
  world:
    name: world
    handler: build/lambda/world
    events:
      - httpApi:
          path: /arm64/world
          method: get